spring:
  application:
    name: core-services
    bad_request: 403
    conflict: 409
    success: 200

  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/core_services
    username: root
    password: root

server:
  port: 8081
